### ISSUE TITLE
Instructions for building image manually

### ISSUE THREAD

**Issue by jschilperoord** [doomkin/oracle#1]
Hi,

Is it possible to include instructions for building the image manually ? Also su -c doesn't seem to work in recent versions of docker (1.6).

Thanks,

Jeffrey

**Comment by doomkin** [comment]
Hi, Jeffrey! 

Added instructions for assembly of the image. Fixed Dockerfile: instead of 'su oracle -c' using 'USER oracle'.

Best regards,
Pavel
